let fruits = 100;
let vegetables = 150;
let Total = fruits+vegetables;
let fr = document.getElementById('fruit');
fr.textContent = fruits;
let ve = document.getElementById('vegetable');
ve.textContent = vegetables;
let to = document.getElementById('total')
to.textContent = Total